using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MathFun.Api.Models
{
    /// <summary>
    /// Represents a REST response to an expression request.
    /// </summary>
    public class ExpressionResponse : ExpressionRequest
    {
        /// <summary>
        /// Gets or sets the parsed and normalized mathematic expression.
        /// </summary>
        public string AdjustedExpression { get; set; }

        /// <summary>
        /// Gets or sets the value generated by the MathExpression.
        /// </summary>
        public decimal ValueGenerated { get; set; }
    }
}
